#!/bin/bash

# show OS and firmware versions
echo -e "\n OS & Firmware versions:\n"
dmesg --notime  | grep firmware
uname -s -r -v -o

# show scripts and python files
echo -e "pidesktop\n\n Script files:\n"
ls -laR /usr/share/pidesktop/*

# show links to pd- commands
echo -e "\n Links to commands:\n"
ls -la /usr/bin/pd-*

# show pidesktop sevices
echo -e "\n Systemd services:\n"
systemctl --plain --no-legend list-unit-files 'pidesktop-*'

# show system and RTC clock details
echo -e "\n System and hardware clocks:\n"
timedatectl status

# show installed version
echo -e "\n Package status:\n"
dpkg -s pidesktop-base
