#!/bin/bash

# files are cleaned up by package manager, but broken links need to be cleared
sudo rm -f /usr/bin/pd-check
sudo rm -f /usr/bin/pd-clonessd
sudo rm -f /usr/bin/pd-bootssd
sudo rm -f /usr/bin/pd-fixrtc

# stop systemd services
sudo systemctl stop pidesktop-powerkey.service
sudo systemctl stop pidesktop-reboot.service
sudo systemctl stop pidesktop-shutdown.service
sudo systemctl disable pidesktop-powerkey.service
sudo systemctl disable pidesktop-reboot.service
sudo systemctl disable pidesktop-shutdown.service

# remove any residual systemd files
sudo rm -f /lib/systemd/system/pidesktop-*.service
sudo rm -f /etc/systemd/system/*.target.wants/pidesktop-*.service

# other changes to consider... TODO: automate this
echo "NOTE: The file /boot/config.txt may leave RTC enabled"
