#!/bin/bash

# files are cleaned up by package manager, but broken links need to be cleared
sudo rm -f /usr/bin/pdx-check
sudo rm -f /usr/bin/pdx-clonessd
sudo rm -f /usr/bin/pdx-bootssd
sudo rm -f /usr/bin/pdx-fixrtc

# stop systemd services
sudo systemctl stop pdx-powerkey.service
sudo systemctl stop pdx-reboot.service
sudo systemctl stop pdx-poweroff.service
sudo systemctl disable pdx-powerkey.service
sudo systemctl disable pdx-reboot.service
sudo systemctl disable pdx-poweroff.service

# remove any residual systemd files
sudo rm -f /lib/systemd/system/pdx-*.service
sudo rm -f /etc/systemd/system/*.target.wants/pdx-*.service

# other changes to consider... TODO: future RTC support cleanup
#echo "NOTE: The file /boot/config.txt may leave RTC enabled"
